apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-db-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: user-db
  template:
    metadata:
      labels:
        app: user-db
    spec:
      containers:
        - name: user-db-container
          image: postgres:18-alpine
          envFrom:
            - secretRef:
                name: user-secret
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: user-db-data
      volumes:
        - name: user-db-data
          persistentVolumeClaim:
            claimName: user-db-data
---
apiVersion: v1
kind: Service
metadata:
  name: user-db
spec:
  selector:
    app: user-db
  ports:
    - port: 5432